version: '3'
services: 
  postgresql:
    image: postgres
    container_name: blog-vue-nest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_HOST=localhost
      - POSTGRES_USER=blog-vue-nest
      - POSTGRES_PASSWORD=blog-vue-nest
      - POSTGRES_DATABASE=blog-vue-nest
    command: postgres
    restart: always

  redis:
    image: redis:alpine3.14
    container_name: redis-blog-vue-nest
    ports:
      - "6379:6379"